set guifont=Monaco:h18            " Font family and font size.
set antialias                     " MacVim: smooth fonts.
set encoding=utf-8                " Use UTF-8 everywhere.
set guioptions-=T                 " Hide toolbar.
set lines=25 columns=100          " Window dimensions.

set guioptions-=r 
